### ISSUE TITLE
Issue making sdgio.obo in release pipeline

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#65]
Error excerpt below - seems to be an OBO file export. @cmungall I remember seeing something similar in Berkeley, is this the same case?

```
[...]
WARNING: the axiom is not translated : SubClassOf(<http://purl.obolibrary.org/obo/OBI_0000339> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/BFO_0000015> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/IAO_0000104>)))
java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1484)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1428)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1398)
        at org.coode.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:65)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:364)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:219)
        at org.coode.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:76)
        at org.coode.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:74)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:438)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:143)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48)
usage: robot [command] [options] <arguments>
 -h,--help             print usage information
 -noprefixes           do not use default prefixes
 -p,--prefix <arg>     add a prefix 'foo: http://bar'
 -P,--prefixes <arg>   use prefixes from JSON-LD file
 -v,--version          print version information
commands:
 help            print help for command
 annotate        annotate ontology
 convert         convert ontology
 diff            find the differences between two ontologies
 export-prefixes export prefixes to a file
 extract         extract terms from an ontology
 filter          filter ontology axioms
 merge           merge ontologies
 reason          reason ontology
 template        build an ontology from a template
Makefile:32: recipe for target 'sdgio.obo' failed
make: *** [sdgio.obo] Error 1
```

**Comment by pbuttigieg** [comment]
@cmungall  removed the dependency on OBO files in ef2a69d324512a43c1c347bd42756bdd0213e88f (unclear if we even need OBO files). Process works now. New release in 89b4b95363ddeacce62beaaf41f0a6ea6c40307c
